services:
  db:
    image: postgres:latest
    networks:
      - app_network
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=concrete_ai_test
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  db_migration:
    build: ./db_migrate
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@0.0.0.0:5432/concrete_ai_test
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.0.2
    depends_on:
      db:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://postgres:postgres@db:5432/concrete_ai_test"
      POSTGRESQL_TABLE_SCHEMA: "auth"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
  account_manager:
    build: ./account_manager
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully
      supertokens:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@0.0.0.0:5432/concrete_ai_test
      - API_DOMAIN=http://0.0.0.0:8080
      - API_PORT=8080
      - SUPERTOKENS_CORE_URI=http://0.0.0.0:3567
      - SUPERTOKENS_APP_NAME=account_manager
    volumes:
      - ./prisma:/usr/src/app/prisma
  payment_manager:
    build: ./payment_manager
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
      db_migration:
        condition: service_completed_successfully
      supertokens:
        condition: service_started
    ports:
      - 8081:8081
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@0.0.0.0:5432/concrete_ai_test
      - API_DOMAIN=http://0.0.0.0:8081
      - API_PORT=8081
      - SUPERTOKENS_CORE_URI=http://0.0.0.0:3567
      - SUPERTOKENS_APP_NAME=payment_manager
    volumes:
      - ./prisma:/usr/src/app/prisma
networks:
  app_network:
    driver: bridge